CREATE TABLE sensor_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pH FLOAT NOT NULL,
    turbidity FLOAT NOT NULL,
    tds FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voltage FLOAT NOT NULL,
    current FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
